// REFERENCIA: [0]=PREGUNTA, [1][2][3]=RESPUESTAS, [4]=POSICION DE LA RESPUESTA CORECTA
const questions = [
  ["¿Cuantos años duro la guerra de los 100 años?","116 Años","100 Años","120 Años", 1],
  ["¿Cual es el tiburon mas grande del mundo?","Tiburon Ballena","Tiburon Blanco","Tiburon Tigre", 1],
  ["¿Cual es el segundo pais mas grande del mundo?","China","Canada","Rusia",2],
  ['¿De que estilo artistico es la "Gioconda"?',"Barroco","Romanticismo","Renacimiento", 3],
  ["¿Que personaje literario ha sido mas veces adaptado al cine?","Sherlock Holmes","Tarzan","Dracula", 1],
  ["¿En que oceano se encuentra el Triangulo de las Bermudas?","Oceano Pacifico","Oceano indico","Oceano Atlantico", 3],
  ["¿En la frontera de que dos paises se ubica el Everest?","Nepal y Rusia","Nepal y China","China e India", 2],
  ["¿Que clase de abeja NO tiene aguijon?","Las obreras","La Reina","Los zanganos", 3],
  ["¿En donde se localiza la mina mas profunda del mundo?","Rusia","Sudamerica","Sudafrica", 3],
  ["¿A partir de que acontecimiento historico se inicio la Edad Contemporanea?","Revolucion Francesa","Revolucion Española","Revolucion Rusa",1],
  ["¿Que tipo de desarrollo embrionario poseen la mayoria de los mamiferos?","Viviparo","Oviparo","Ovoviviparo", 1],
  ['¿Quien escribio la novela "1984"?',"Stephen King","George Orwell","Ray Bradbury", 2],
  ["¿Cual de estos tres paises NO tiene desierto?","Libia","Alemania","España", 2],
  ["¿Quien es apodado como 'El Rey del Rock and Roll'?","Chuck Berry","Jerry Lee Lewis","Elvis Presley", 3],
  ["¿En que pais se localiza el Bosque Rojo del Kuban?","Rusia","Guinea","Camboya", 1],
  ["¿Que material funciona como un aislante electrico?","Cobre","Madera","Aluminio", 2],
  ["¿De que estilo arquitectonico es la Catedral de Notre Dame?","Barroco","Gotico","Romanico", 2],
  ["¿Cual es la isla mas grande del mundo?","Madagascar","Borneo","Groenlandia", 3],
  ["¿Quien es el director de la pelicula de 1997 'Titanic'?","Steven Spielberg","James Cameron","Roland Emmerich", 2],
  ["¿Que imperio fue el mas grande durante el siglo XIX?","Imperio Aleman","Imperio Español","Imperio Britanico", 3],
  ["¿En que pais se encuentra la famosa 'Catedral de San Basilio'?","Rusia","Alemania","Austria", 1],
  ["¿Cuantos años tiene un lustro?","Cinco","Cincuenta","Quinientos", 1],
  ['¿A que diosa griega esta dedicado el templo "El Partenon"?',"Afrodita","Artemis","Atenea", 3],
  ["¿En que año se produjo el accidente nuclear de Chernobil?","1980","1986","1990", 2],
  ["¿Cuantos paises conforman el continente americano (Sur,Centro y Norte)?","32","35","38", 2],
  ["¿Quien es el creador de la fomasa serie 'Los Simpsin'?","Matt Groening","Sam Simon","Dan Castellaneta", 1],
  ["¿Cual es el rio mas largo del mundo?","Nilo","Amazonas","Yangtse", 2],
  ["¿Que pais exporto al mundo el arte marcial 'Muay Thai?","Tailandia","Japon","China", 1],
  ["¿En que ciudad Italiana se encuentra la Fontana di Trevi?","Napoles","San Marino","Roma", 3],
  ["¿Cuantas etapas hay en el ciclo de vida de una mariposa?","4","5","3", 1],
  ["¿En que año se inicio la Primera Guerra Mundial?","1912","1914","1916", 2],
  ["¿Cual es el principal componente quimico de la lavandina?","Amoniaco","Fluor","Cloro", 3],
  ['¿En que pais africano se encuentra el "Kilimanjaro"?',"Tanzania","Kenia","Zambia", 1],
  ["¿En donde nacio Adolf Hitler?","Alemania","Austria","Australia", 2],
  ["¿En que año tuvo lugar la primera gala de los Premios Oscar?","1929","1945","1971", 1],
  ["¿En que oceano se encuentra la Fosa de las Marianas?","Indico","Atlantico","Pacifico", 3],
  ["¿En que libro de la 'Biblia' se narra la historia de Adan y Eva?","Genesis","Exodo","Levitico", 1],
  ["¿Que deporte de combate creo Jigoro Kano?","Taekwondo","Judo","Kickbocing", 2],
  ["¿En que continente se localizan las sierras Subandinas?","Europa","Asia","Sudamerica", 3],
  ["¿En que pais se localiza 'La Pampa?","Argentina","Colombia","Brasil", 1],
  ["¿Cual fue el primer elemento quimico descubierto cientificamente?","Nitrogeno","Fosforo","Cesio", 2],
  ['¿En que pais se invento la "Esgrima"?',"Alemania","Francia","España", 3],
  ["¿Que obra NO es de William Shakespeare?","McBeth","Tristan e Isolda","Romeo y Julieta", 2],
  ["¿En que unidad se mide la intensidad del sonido?","Vatios","Watts","Decibelios", 3],
  ["¿Que forma de gobierno se crea tras la Revolucion Francesa?","Feudalismo","Liberalismo","Fascismo", 2],
  ["¿En que pais se encuentra el volcan Cotopaxi?","Ecuador","Mexico","Uruguay", 1],
  ["¿Que dos elementos descubrio Marie Curie?","Plutonio y Curio","Polonio y Radio","Uranio y Radon", 2],
  ['¿En que pais tuvo lugar la "Guerra de los Mil Dias" disputada entre 1899 y 1902?',"Colombia","Mexico","Venezuela", 1],
  ["¿A que pais pertenece la Isla de Creta?","Italia","Turquia","Grecia", 3],
  ["¿De que grupo era vocalista Jim Morrison?","Nirvana","Pink Floyd","The Doors", 3],
  ['¿Quien compuso el famoso "Lago de los Cisnes"?',"Tchaikovski","Mozart","Vivaldi", 1],
  ["¿En que año fallecio Fidel Castro?","2014","2016","2018", 2],
  ['¿A las funciones de que organo sustituye una "Hemodialisis"?',"Bazo","Higado","Riñones", 3],
  ["¿Como se llama el triangulo que tiene dos lados iguales y uno diferente?","Isosceles","Escaleno","Equilatero", 1],
  ["¿Que videoconsola es la mas vendida de todos los tiempos?","Game Boy","Nintendo Wii","PlayStation 2", 3],
  ["¿A que pais pertenece la Isla de Pascua?","Argentina","Chile","Paraguay", 2],
  ["¿Que pais ha ganado mas mundiales de futbol?","Alemania","Argentina","Brasil", 3],
  ['¿Quien pinto "Las Meninas"?',"Diego Velazquez","Francisco de Goya","Salvador Dali", 1],
  ["¿En que año se produjo el ataque a Pearl Harbor?","1940","1941","1942", 2],
  ["¿Cual es el simbolo quimico del Estaño?","Es","Sb","Sn", 3],
  ["¿Que cantante esta considerado como el 'Padrino del Soul'?","Marvin Gaye","James Brown","Stevie Wonder", 2],
  ["¿Donde se encuentra el mayor arrecife del mundo?","Australia","Belice","Indonecia", 1],
  ['¿En que año se publico el famoso "Diario de Ana Frank"?',"1947","1950","1952", 1],
  ["¿Cual es el unico felino que no tiene garras retractiles?","Tigre","Guepardo","Puma", 2],
  ["¿En que año se produjo el atentado a las Torres Gemelas?","2000","2002","2001", 3],
  ["¿En que año se hundio el Titanic?","1910","1912","1914", 2],
  ["¿Que pais se encuentra en el hesmiferio sur?","España","Japon","Nueva Zelanda", 3],
  ["¿Cual de estas peliculas NO esta basada en una novela?","Interestellar","Parque Jurasico","Yo, robot", 1],
  ["¿Que componente da a la sangre su caracteristico color rojo?","Los Hematies","Los Leucocitos","La Hemoglobina", 3],
  ["¿En que año se produjo 'La Caida del Muro de Berlin'?","1986","1989","1991", 2],
  ["¿Que pais NO se encuentra en el 'circulo polar Artico'?","Canada","Rusia","Nepal", 3],
  ["¿A que pais pertenece Gibraltar?","Reino Unido","España","Francia", 1],
  ["¿En que genero destacan las obras literarias de Edgar Allam Poe?","Comedia","Drama","Terror", 3],
  ["Quien fue la primera mijer en recibir un Premio Nobel?","Bertha Von Suttner","Marie Curie","Grazia Deledda", 2],
  ["¿A que grupo de rock pertenece el cantante Axl Rose ?","Guns N' Roses","Nirvana","Red Hot Chili Peppers", 1],
  ["¿A cuanto tiempo equivale un 'Decalustro'?","15 Años","25 Años","50 Años", 3],
  ["¿Cual de estos pintores fue tambien un escultor?","Rafael","El Greco","Miguel Angel", 3],
  ["¿Quien fue el inventor de la bombilla?","Thomas Edison","Nikola Tesla","Albert Einstein", 1],
  ["¿Que actor NUNCA ha interpretado al Agente James Bond ?","Robert Redford","Sean Connery","Roger Moore", 1],
  ["¿Cuantos torneos de Grand Slam ha ganado el tenista Raga Nadal hasta 2019?","14","17","19", 2],
  ["¿Cuantos huesos tiene el cuerpo humano adulto?","206","212","216", 1],
  ["¿A que provincia Argentina pertenece el Parque Nacional Talampaya?","Catamarca","San Juan","La Rioja", 3],
  ["¿Que saga de libros es la mas vendida?","El señor de los Anillos","Harry Potter","Canción de hielo y fuego", 2],
  ["¿Que sistema politico predomino en la Europa Occidental de la Edad Media?","Capitalismo","Feudalismo","Comunismo", 2],
  ["¿Cual es el deporte que mas se practica en el mundo?","Natacion","Tenis","Futbol", 1],
  ["¿Que se almacena en los conductos linfaticos?","Globulos rojos","Globulos blancos","Plaquetas", 2],
  ["¿De que material esta hecha la famosa escultura 'Venus de Milo'?","Piedra caliza","Bronce","Marmol", 3],
  ["¿Cuales son los 2 idiomas oficiales que se hablan en Canada?","Ingles y Español","Ingles y Frances","Ingles e Italiano", 2],
  ["¿Cual de estos animales es un anelido?","Lombriz","Pulpo","Cucaracha", 1],
  ["¿En que año se abrio el Canal de Panama?","1889","1905","1914", 3],
  ["¿Cuanto mide de alto la Muralla China?","De 3 a 5 metros","De 6 a 7 metros","De 8 a 9 metros", 2],
  ["¿Cual de estas estrllas es la mas cercana al Sistema Solar?","Polux","Estrella Polar","Proxima Centauri", 3],
  ["¿En que siglo invento el primer telescopio?","Siglo XVII","Siglo XII","Siglo IX", 1],
  ["¿En que pais se encuentra la antigua ciudad de Petra?","Siria","Jordania","Irak", 2],
  ["¿Quien pinto el famoso fresco 'La Creacion de Adan'?","Leonardo da Vinci","Rafael Sanzio","Miguel Angel", 3],
  ["¿En que año comenzo la 'Batalla de Stalingrado'?","1939","1942","1940", 2],
  ["¿Contra que imperio lucho Leonidas en la Batalla de las Termopilas?","Persia","Macedonia","Tracia", 1],
  ["¿De que material esta hecha la famosa 'Estatua de la Libertad' ubicada en Estados Unidos","Hierro","Acero","Bronce", 3],
  ["¿En que año acabo la Segunda Guerra Mundial?","1945","1942","1946", 1],
  ["¿Como se llama la desgada capa de tejido elastico que recubre los extremos de los huesos?","Tendones","Cartilagos","Ligamentos", 2],
  ['¿Quien escribio la novela de fantasia "Alicia en el pais de las Maravillas"?',"Oscar Wilde","Lewis Carroll","James Joyce", 2],
  ["¿Cual de estas unidades de medida no pertenece a las unidades electricas?","Ohm","Volt","Dina", 3],
  ["¿En que museo se encuentra el 'Guernica' de Picasso?","Museo Reina Sofia","Museo del Prado","Moseo Picasso", 1],
  ["¿Que nombre recibe el proceso por el cual un gas pasa a ser solido?","Sublimacion Progresiva","Solidificacion","Sublimacion Regresiva", 3],
  ["¿A que dios Egipcio se lo relacionaba con la muerte y la momificacion?","Amon","Anubis","Isis", 2],
  ["¿Cual fue el primer emperador Romano?","Augusto","Caligula","Neron", 1],
  ["¿De que estilo arquitectonico es el 'Arco del Triunfo de Paris'?","Barroco","Neoclasico","Gotico", 2],
  ["¿Cual de estas sagas literarias aun en 2022 NO fue adaptada al Cine?","El Señor de los Anillos","Las crónicas de Narnia","Canción de hielo y fuego",3],
  ["¿Cual es la ciudad mas poblada de Sudamerica?","Bogota","Buenos Aires","Sao Pablo", 3],
  ['¿Cual de estos escritores NO formo parte en la escritura de la saga "La Rueda del Tiempo"?',"George R.R. Martin","Brandon Sanderson","Robert Jordan",1]
];